config/routes.rb
Rails.application.routes.draw do
  resources :finds 
  resources :profiles 
  get 'profiles/search'
  resources :posts
  devise_for :users
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_one_attached :video


  
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile
  has_many :posts 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         DISTRICT = ['select-district/village', 'Popodara', 'Gongore-Aideh', 'Gongore-centre', 'Poukou', 'Kourou']
         GENDER = ['select-gender','Male', 'Female']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?



    protected 
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:age, :gender,:username,:district,:residence,:profile,:search])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :age, :gender, :username, :district,:residence,:profile])
    end

end

app/controllers/finds_controller.rb
class FindsController < ApplicationController
  def index
    @members = if params[:search]
      User.where('name LIKE ?', "%#{params[:search]}%")
    
       
      else
       User.all data:{notice:'no match fro'}

      end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @post = Post.new
    @posts = Post.order('created_at DESC')
  
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image, :video).merge(user_id: current_user.id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.all 
      
  end

  def search
 
  end



  def show 
    @user = User.find(params[:id])
  end 




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finds_helper.rb
module FindsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/finds/index.html.erb
<p id="notice"><%= notice %></p>

<div class= 'member'>
<h3>People you may know</h3>
<% @members.each do |m| %>
<div class='innermember'>

<%= link_to image_tag(m.profile, size:'90x90', style:'border-radius: 50%', class:'findimg'),profile_path(m) %>
<p id='findname'><%= link_to m.name,profile_path(m) %></p>
<p><em><%=m.district%></em></p>
</div>

<% end %>
 
 
</div>

app/views/layouts/_nav.html.erb
<nav>
<%= form_tag(finds_path,class:'search', method: :get) do %>
<%= text_field_tag(:search, params[:search],placeholder:'search for members',id:'input') %>
<%= submit_tag "search",class:'searchbutton', name: nil %>
<% end %>

  <% if user_signed_in? %>
   <div class='pro'>
   <%= link_to image_tag(current_user.profile, size:'40x40', style:"border-radius:75%"), profile_path(current_user) %>
  </div>
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
 <%= link_to 'members', profiles_path, class:'nav' %>
    <%= link_to 'home', posts_path %>

</nav>

app/views/layouts/_notice.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gongoreinc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'jquery' %>
 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
   
  </head>

  <body>
  <%= render 'layouts/nav' %>



  <%= render 'layouts/notice' %>
<% flash.each do |key, value| %>
  <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_create.html.erb
<div class='postform'>

    <%= form_with(model: @post, class:'form') do |f| %>
   
    <%= f.text_field :title,placeholder:'what is your post about?',class:'input',id:'title' %> <br>
    <%= f.text_area :content,rows:3, placeholder:'share your post here',class:'input',id:'content' %> <br>

    <p>Photo<%= f.file_field :image, placeholder:'photo', class:'input' %></p>
   <p>Video<%= f.file_field :video,class:'input' %></p> 
    <%= f.submit 'upload', id:'upload' %>
    <%end%>





</div>

app/views/posts/_form.html.erb
<div class='postform' >
<%= form_with(model: post, local: true, class:'form') do |form| %>

  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :About %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    
    <%= form.text_area :content, placeholder: 'share your post here', rows:4, styles:'border-radius:5px' %>
  </div>
  <div class='field'>
  <%=form.label :Image_upload %>
  <%=form.file_field :image %>
   <%=form.label :Video_upload %>
  <%=form.file_field :video %>
  </div>

 

  <div class="actions">
    <%= form.submit 'upload' %>
  </div>
  
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>


<%= render 'create'%>


 <div class='indexpost'>
 
    <% @posts.each do |post| %>
<div class="individual">    
<div class='headpost'>
         
         <%= link_to image_tag(post.user.profile, size:'40x40', style:'border-radius:50%'), profile_path(post.user) %> 
         <strong class='username'><%= link_to post.user.name, profile_path(post.user)%></strong> 
</div>
        <%= post.title %> <br>
        <%= post.content %> <br>
        <% if post.image.attached? %>
        <%= image_tag post.image, size:'350x300',class:'photo' %> <br>
        <%end%>
        <% if post.user_id != current_user.id %>
        <%= link_to 'Show', post %>
        <% else %>
        <button id="btn"><%= link_to 'Show', post %></button>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
      
      <%end %>
      </div>
    <% end %>
    
    


    </div>
  








<script src="assets/javascripts/posts.js"></script>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%=@post.user.name%></strong> <br>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>
<% if @post.image.attached? %>

  <p>
    <strong>Photo:</strong>
    <br>
    <%= image_tag @post.image, size:'350x300' %>
  </p>
<% end %>

<% if @post.video.attached? %>
<!-- @post.image.present? will always return true, use attached? to check presence -->
  <p>
    <strong>Video:</strong>
    <br>
    <%= video_tag(url_for(@post.video), size:'400x300', controls: '') %>
  </p>
<% end %>
<% if @post.id == current_user.id %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<% else %>
<%= link_to 'Back', posts_path %>
<% end %>

app/views/profiles/index.html.erb
<h1>Members</h1>
<div class = 'users'>
<div class='profile'>
    <% @users.each do |user| %>

    <% if user.profile.attached? %>
    
<%= link_to image_tag(user.profile,size:'50x50', style:"border-radius:75%"),profile_path(user) %><strong>
<% end %>
<%= link_to  user.name ,profile_path(user), class:'name'%> </strong>  
 <hr>   
 <% end %> 
 </div>

    
</div>

app/views/profiles/show.html.erb
<div class='userprofile'>
<% if @user.profile.attached? %>
<%= image_tag @user.profile, size:'300x300', style:'border-radius:10%'%>
<% end %>
<div class='innerdivprofile'>
   Name :<strong><%= @user.name %></strong> 
</div>
<div class='innerdivprofile'>
 Resides in:   <strong><%= @user.residence %></strong> 
</div>
<div class='innerdivprofile'>
  District/Village: <strong><%= @user.district %></strong> <br>
</div>
<div class='innerdivprofile'>
  Gender: <strong><%= @user.gender %></strong> <br>
  Birthday: <strong><%=@user.age.strftime("%m-%d-%Y") %></strong>
</div>
<div class='userprofileposts'>
<h3>Member Posts</h3>
    <% @user.posts.each  do |post| %>
    
    <strong>About</strong><%=post.title%> <br>
    <strong>Post Content:</strong><%= post.content %> <br>
    <strong>Posted at:</strong><%= time_ago_in_words(post.created_at) %>
    <div>
    <% if post.image.attached? %>
     <h3>Member photos Posts</h3>
    <%= image_tag post.image, size:'450x350' %> <br>
    <strong>Posted at:</strong><%= time_ago_in_words(post.created_at) %>
<% end %>
</div>
<div> 
    <% if post.video.attached? %>
    <h3>Member videos posts</h3>
    <%= video_tag(url_for(post.video), size:'450x350', controls:'') %>  <br>
    <strong>Posted at:</strong><%= time_ago_in_words(post.created_at) %>
<% end %>
   
</div>

    <% end %>
</div>
</div>